[build]
target = "index.html"
dist = "dist"
release = false

[tools]
tailwindcss = "4.2.0"

[serve]
addresses = ["0.0.0.0"]
port = 8080

[watch]
watch = ["src", "index.html", "input.css"]

[[proxy]]
backend = "http://server:3000/api/"
rewrite = "/api/"
