[build]
target = "index.html"
dist = "dist"
release = true

[tools]
tailwindcss = "4.2.0"

[serve]
addresses = ["0.0.0.0"]

[watch]
watch = ["src", "index.html", "input.css"]

[[proxy]]
backend = "http://localhost:3000/api/"
rewrite = "/api/"
